[build]
  functions = "functions"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[functions.node_js_build_mode]
  external_node_modules = ["node-fetch"]

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
